services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - app
    environment:
      POSTGRES_USER: "wineskills"
      POSTGRES_PASSWORD: "wineskills"

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app

  minio:
    image: bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app
    volumes:
      - "minio:/bitnami/minio/data"
    environment:
      - MINIO_ROOT_USER=wineskills
      - MINIO_ROOT_PASSWORD=wineskills
      - MINIO_DEFAULT_BUCKETS=wineskills

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - app
    ports:
      - 9200:9200

networks:
  app:
    driver: bridge

volumes:
  minio:
    driver: local
