services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "wineskills"
      POSTGRES_PASSWORD: "wineskills"

  redis:
    image: redis:latest
    ports:
      - 6379:6379
